# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SentinelUpscaling
                                 A QGIS plugin
 Esse plugin realiza downloads e upscaling de imagens do satelite Sentinel 2
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-04-12
        copyright            : (C) 2021 by Guilherme Rodrigues Sganderla
        email                : grodriguessganderla@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SentinelUpscaling class from file SentinelUpscaling.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .sentinel_upscaling import SentinelUpscaling
    return SentinelUpscaling(iface)
